In [2]:
 import numpy as np

# arange()

In [11]:
array_1 = np.arange(1,13) #  create array.
print(array_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# linspace()

In [4]:
array_2 = np.linspace(1,5,4) # for creat array.
print(array_2)

[1.         2.33333333 3.66666667 5.        ]


# reshape()

In [12]:
array_1d = array_1.reshape(2,6) # 1d array convert into 2d or 3d array.(row,colum,rowvlaue)
print(array_1d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [13]:
array_1d.ravel() #2d array convert into 1d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [14]:
array_1d.flatten() # 2d array convert into 1d array with argument

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [15]:
array_1.transpose() # row convert into column short cut use .T sing.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])